# Copyright (c) 2016. TIBCO Software Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
# version: 6.3.0-v1.0.4

version: '3.1'

# network used by both JasperReports Server and PostgreSQL containers
networks:
  default:
    ipam:
      config:
        - subnet: "192.168.5.1/24"

services:
  jasperserver:
    # to build instead of using image
    # - change version towards top of file from 3.1 to 2
    # - comment image line
    # - uncomment build line
    image: bbustin/js-docker-bigquery
    # build: .

    # expose port 8080 and bind it to 8080 on host
    ports:
      - "8080:8080"
      - "8443:8443"
    # set depends on js_database service
    depends_on:
      - js_database
    # point to env file with key=value entries 
    env_file: .env
    # setting following values here will override settings from env_file
    environment:
      - DB_HOST=js_database
  js_database:
    image: postgres:9.4
    env_file: .env

volumes:
  jrs_license:
  jrs_customization:
